### ISSUE TITLE
Support Chromium-based Edge

### ISSUE THREAD

**Issue by Thunderforge** [TheDavidDelta/myJDoc#1]
Microsoft's Chromium-based Edge (i.e. Edge 79.x and later) is currently in beta and release candidate channels, and will be available for general release on January 15, 2020.

[These porting guidelines](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions) show how to have a Chrome extension work on Microsoft Edge, and appears to be a very simple process. It would be great to have this support finished before the browser's general release.

After that, it would just be a matter of [publishing the extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension).

**Comment by thedaviddelta** [comment]
I'd like to tell you that I'm working on it.
Today I've been building the port and it works correctly on Edge but I have an strange error on publishing that I've already reported on a ticket.

**Comment by thedaviddelta** [comment]
Microsoft just accepted myJDoc on new Edge, it's already available to download [here](https://microsoftedge.microsoft.com/addons/detail/lbckjgnglclmejkildjjkpphkmlgkdfl).

I also published [my other extension](https://github.com/TheDavidDelta/mySkip) inthere.
